# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 779b135473da28c2735a022435f5612726ec85fc9baeee61677d7616442243671ffe2fb026c539b2045f5d9875f3569898fbde75893074fe7f1213daca06f22f

test:
  secret_key_base: 5b247f4bacea46fe536dd277ecb333322c52f460b13a51c11c79b22bf93e2bffac412abea869c65d991843657ce826a00cb1ca596278bf5e685be960d29311ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
